// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: pkg/grpcapi/api.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_QUEUED   TaskStatus = 0
	TaskStatus_STARTED  TaskStatus = 1
	TaskStatus_COMPLETE TaskStatus = 2
	TaskStatus_FAILED   TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "QUEUED",
		1: "STARTED",
		2: "COMPLETE",
		3: "FAILED",
	}
	TaskStatus_value = map[string]int32{
		"QUEUED":   0,
		"STARTED":  1,
		"COMPLETE": 2,
		"FAILED":   3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpcapi_api_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_pkg_grpcapi_api_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{0}
}

type TaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data           string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Task timeout in seconds
	RetryCount     int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`             // Current retry attempt (for logging)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`                                 // Task output (stdout)
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ClientTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Data              string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Priority          int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`                                              // 1-10, lower = higher priority (default 5)
	MaxRetries        int32                  `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`                        // Max retry attempts (default 3)
	RetryDelaySeconds int32                  `protobuf:"varint,4,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3" json:"retry_delay_seconds,omitempty"` // Delay between retries (default 60)
	TimeoutSeconds    int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`            // Task timeout (default 300)
	ScheduledAt       int64                  `protobuf:"varint,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`                     // Unix timestamp for delayed execution (0 = now)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientTaskRequest) Reset() {
	*x = ClientTaskRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTaskRequest) ProtoMessage() {}

func (x *ClientTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTaskRequest.ProtoReflect.Descriptor instead.
func (*ClientTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{2}
}

func (x *ClientTaskRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ClientTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ClientTaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *ClientTaskRequest) GetRetryDelaySeconds() int32 {
	if x != nil {
		return x.RetryDelaySeconds
	}
	return 0
}

func (x *ClientTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ClientTaskRequest) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

type ClientTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTaskResponse) Reset() {
	*x = ClientTaskResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTaskResponse) ProtoMessage() {}

func (x *ClientTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTaskResponse.ProtoReflect.Descriptor instead.
func (*ClientTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      uint32                 `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetWorkerId() uint32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=grpcapi.TaskStatus" json:"status,omitempty"`
	StartedAt     int64                  `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	FailedAt      int64                  `protobuf:"varint,5,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	Output        string                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`                                 // Task output
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_QUEUED
}

func (x *UpdateTaskStatusRequest) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *UpdateTaskStatusRequest) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *UpdateTaskStatusRequest) GetFailedAt() int64 {
	if x != nil {
		return x.FailedAt
	}
	return 0
}

func (x *UpdateTaskStatusRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShouldRetry   bool                   `protobuf:"varint,2,opt,name=should_retry,json=shouldRetry,proto3" json:"should_retry,omitempty"` // Tell worker if it should retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusResponse) Reset() {
	*x = UpdateTaskStatusResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusResponse) ProtoMessage() {}

func (x *UpdateTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTaskStatusResponse) GetShouldRetry() bool {
	if x != nil {
		return x.ShouldRetry
	}
	return false
}

type WorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType  string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"` // JSON context passed to step templates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRequest) Reset() {
	*x = WorkflowRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRequest) ProtoMessage() {}

func (x *WorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRequest.ProtoReflect.Descriptor instead.
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WorkflowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStatusRequest) Reset() {
	*x = WorkflowStatusRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatusRequest) ProtoMessage() {}

func (x *WorkflowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatusRequest.ProtoReflect.Descriptor instead.
func (*WorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowStatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type WorkflowStepInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StepNumber         int32                  `protobuf:"varint,1,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TaskId             string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CompensationTaskId string                 `protobuf:"bytes,5,opt,name=compensation_task_id,json=compensationTaskId,proto3" json:"compensation_task_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowStepInfo) Reset() {
	*x = WorkflowStepInfo{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStepInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStepInfo) ProtoMessage() {}

func (x *WorkflowStepInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStepInfo.ProtoReflect.Descriptor instead.
func (*WorkflowStepInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{11}
}

func (x *WorkflowStepInfo) GetStepNumber() int32 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *WorkflowStepInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowStepInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStepInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WorkflowStepInfo) GetCompensationTaskId() string {
	if x != nil {
		return x.CompensationTaskId
	}
	return ""
}

type WorkflowStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   int32                  `protobuf:"varint,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Context       string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Steps         []*WorkflowStepInfo    `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStatusResponse) Reset() {
	*x = WorkflowStatusResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatusResponse) ProtoMessage() {}

func (x *WorkflowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkflowStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{12}
}

func (x *WorkflowStatusResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowStatusResponse) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStatusResponse) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *WorkflowStatusResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *WorkflowStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WorkflowStatusResponse) GetSteps() []*WorkflowStepInfo {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *WorkflowStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WorkflowStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_pkg_grpcapi_api_proto protoreflect.FileDescriptor

const file_pkg_grpcapi_api_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/grpcapi/api.proto\x12\agrpcapi\"\x84\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\"\x98\x01\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xe0\x01\n" +
	"\x11ClientTaskRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12.\n" +
	"\x13retry_delay_seconds\x18\x04 \x01(\x05R\x11retryDelaySeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12!\n" +
	"\fscheduled_at\x18\x06 \x01(\x03R\vscheduledAt\"G\n" +
	"\x12ClientTaskResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"H\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\rR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xfb\x01\n" +
	"\x17UpdateTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.grpcapi.TaskStatusR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x04 \x01(\x03R\vcompletedAt\x12\x1b\n" +
	"\tfailed_at\x18\x05 \x01(\x03R\bfailedAt\x12\x16\n" +
	"\x06output\x18\x06 \x01(\tR\x06output\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"W\n" +
	"\x18UpdateTaskStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fshould_retry\x18\x02 \x01(\bR\vshouldRetry\"U\n" +
	"\x0fWorkflowRequest\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\"g\n" +
	"\x10WorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"8\n" +
	"\x15WorkflowStatusRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\xaa\x01\n" +
	"\x10WorkflowStepInfo\x12\x1f\n" +
	"\vstep_number\x18\x01 \x01(\x05R\n" +
	"stepNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x120\n" +
	"\x14compensation_task_id\x18\x05 \x01(\tR\x12compensationTaskId\"\xc7\x02\n" +
	"\x16WorkflowStatusResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\x05R\vcurrentStep\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12/\n" +
	"\x05steps\x18\a \x03(\v2\x19.grpcapi.WorkflowStepInfoR\x05steps\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt*?\n" +
	"\n" +
	"TaskStatus\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\f\n" +
	"\bCOMPLETE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032L\n" +
	"\rWorkerService\x12;\n" +
	"\n" +
	"SubmitTask\x12\x14.grpcapi.TaskRequest\x1a\x15.grpcapi.TaskResponse\"\x002\xa3\x03\n" +
	"\x12CoordinatorService\x12G\n" +
	"\n" +
	"SubmitTask\x12\x1a.grpcapi.ClientTaskRequest\x1a\x1b.grpcapi.ClientTaskResponse\"\x00\x12H\n" +
	"\rSendHeartbeat\x12\x19.grpcapi.HeartbeatRequest\x1a\x1a.grpcapi.HeartbeatResponse\"\x00\x12Y\n" +
	"\x10UpdateTaskStatus\x12 .grpcapi.UpdateTaskStatusRequest\x1a!.grpcapi.UpdateTaskStatusResponse\"\x00\x12G\n" +
	"\x0eSubmitWorkflow\x12\x18.grpcapi.WorkflowRequest\x1a\x19.grpcapi.WorkflowResponse\"\x00\x12V\n" +
	"\x11GetWorkflowStatus\x12\x1e.grpcapi.WorkflowStatusRequest\x1a\x1f.grpcapi.WorkflowStatusResponse\"\x00B.Z,github.com/ChinmayNoob/conductor/pkg/grpcapib\x06proto3"

var (
	file_pkg_grpcapi_api_proto_rawDescOnce sync.Once
	file_pkg_grpcapi_api_proto_rawDescData []byte
)

func file_pkg_grpcapi_api_proto_rawDescGZIP() []byte {
	file_pkg_grpcapi_api_proto_rawDescOnce.Do(func() {
		file_pkg_grpcapi_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpcapi_api_proto_rawDesc), len(file_pkg_grpcapi_api_proto_rawDesc)))
	})
	return file_pkg_grpcapi_api_proto_rawDescData
}

var file_pkg_grpcapi_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_grpcapi_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_grpcapi_api_proto_goTypes = []any{
	(TaskStatus)(0),                  // 0: grpcapi.TaskStatus
	(*TaskRequest)(nil),              // 1: grpcapi.TaskRequest
	(*TaskResponse)(nil),             // 2: grpcapi.TaskResponse
	(*ClientTaskRequest)(nil),        // 3: grpcapi.ClientTaskRequest
	(*ClientTaskResponse)(nil),       // 4: grpcapi.ClientTaskResponse
	(*HeartbeatRequest)(nil),         // 5: grpcapi.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 6: grpcapi.HeartbeatResponse
	(*UpdateTaskStatusRequest)(nil),  // 7: grpcapi.UpdateTaskStatusRequest
	(*UpdateTaskStatusResponse)(nil), // 8: grpcapi.UpdateTaskStatusResponse
	(*WorkflowRequest)(nil),          // 9: grpcapi.WorkflowRequest
	(*WorkflowResponse)(nil),         // 10: grpcapi.WorkflowResponse
	(*WorkflowStatusRequest)(nil),    // 11: grpcapi.WorkflowStatusRequest
	(*WorkflowStepInfo)(nil),         // 12: grpcapi.WorkflowStepInfo
	(*WorkflowStatusResponse)(nil),   // 13: grpcapi.WorkflowStatusResponse
}
var file_pkg_grpcapi_api_proto_depIdxs = []int32{
	0,  // 0: grpcapi.UpdateTaskStatusRequest.status:type_name -> grpcapi.TaskStatus
	12, // 1: grpcapi.WorkflowStatusResponse.steps:type_name -> grpcapi.WorkflowStepInfo
	1,  // 2: grpcapi.WorkerService.SubmitTask:input_type -> grpcapi.TaskRequest
	3,  // 3: grpcapi.CoordinatorService.SubmitTask:input_type -> grpcapi.ClientTaskRequest
	5,  // 4: grpcapi.CoordinatorService.SendHeartbeat:input_type -> grpcapi.HeartbeatRequest
	7,  // 5: grpcapi.CoordinatorService.UpdateTaskStatus:input_type -> grpcapi.UpdateTaskStatusRequest
	9,  // 6: grpcapi.CoordinatorService.SubmitWorkflow:input_type -> grpcapi.WorkflowRequest
	11, // 7: grpcapi.CoordinatorService.GetWorkflowStatus:input_type -> grpcapi.WorkflowStatusRequest
	2,  // 8: grpcapi.WorkerService.SubmitTask:output_type -> grpcapi.TaskResponse
	4,  // 9: grpcapi.CoordinatorService.SubmitTask:output_type -> grpcapi.ClientTaskResponse
	6,  // 10: grpcapi.CoordinatorService.SendHeartbeat:output_type -> grpcapi.HeartbeatResponse
	8,  // 11: grpcapi.CoordinatorService.UpdateTaskStatus:output_type -> grpcapi.UpdateTaskStatusResponse
	10, // 12: grpcapi.CoordinatorService.SubmitWorkflow:output_type -> grpcapi.WorkflowResponse
	13, // 13: grpcapi.CoordinatorService.GetWorkflowStatus:output_type -> grpcapi.WorkflowStatusResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_grpcapi_api_proto_init() }
func file_pkg_grpcapi_api_proto_init() {
	if File_pkg_grpcapi_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpcapi_api_proto_rawDesc), len(file_pkg_grpcapi_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_grpcapi_api_proto_goTypes,
		DependencyIndexes: file_pkg_grpcapi_api_proto_depIdxs,
		EnumInfos:         file_pkg_grpcapi_api_proto_enumTypes,
		MessageInfos:      file_pkg_grpcapi_api_proto_msgTypes,
	}.Build()
	File_pkg_grpcapi_api_proto = out.File
	file_pkg_grpcapi_api_proto_goTypes = nil
	file_pkg_grpcapi_api_proto_depIdxs = nil
}
