// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: pkg/grpcapi/api.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_QUEUED   TaskStatus = 0
	TaskStatus_STARTED  TaskStatus = 1
	TaskStatus_COMPLETE TaskStatus = 2
	TaskStatus_FAILED   TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "QUEUED",
		1: "STARTED",
		2: "COMPLETE",
		3: "FAILED",
	}
	TaskStatus_value = map[string]int32{
		"QUEUED":   0,
		"STARTED":  1,
		"COMPLETE": 2,
		"FAILED":   3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpcapi_api_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_pkg_grpcapi_api_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{0}
}

type TaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data           string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryCount     int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"` // Current retry attempt (for logging)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"` // false if the worker has no free slot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClientTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Data              string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Priority          int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`                                              // 1-10, lower = higher priority (default 5)
	MaxRetries        int32                  `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`                        // Max retry attempts (default 3)
	RetryDelaySeconds int32                  `protobuf:"varint,4,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3" json:"retry_delay_seconds,omitempty"` // Base delay between retries (default 60)
	TimeoutSeconds    int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`            // Task timeout (default 300)
	ScheduledAt       int64                  `protobuf:"varint,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`                     // Unix timestamp for delayed execution (0 = now)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientTaskRequest) Reset() {
	*x = ClientTaskRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTaskRequest) ProtoMessage() {}

func (x *ClientTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTaskRequest.ProtoReflect.Descriptor instead.
func (*ClientTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{2}
}

func (x *ClientTaskRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ClientTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ClientTaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *ClientTaskRequest) GetRetryDelaySeconds() int32 {
	if x != nil {
		return x.RetryDelaySeconds
	}
	return 0
}

func (x *ClientTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ClientTaskRequest) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

type ClientTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTaskResponse) Reset() {
	*x = ClientTaskResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTaskResponse) ProtoMessage() {}

func (x *ClientTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTaskResponse.ProtoReflect.Descriptor instead.
func (*ClientTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False if the task had already finished (or, on a worker, isn't running there).
	Cancelled     bool `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type HeartbeatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId uint32                 `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address  string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// A draining worker finishes its current tasks but accepts no new ones.
	Draining      bool `protobuf:"varint,3,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetWorkerId() uint32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatRequest) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=grpcapi.TaskStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Set when status is FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_QUEUED
}

func (x *UpdateTaskStatusRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldRetry   bool                   `protobuf:"varint,1,opt,name=should_retry,json=shouldRetry,proto3" json:"should_retry,omitempty"` // The coordinator will retry the failed task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusResponse) Reset() {
	*x = UpdateTaskStatusResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusResponse) ProtoMessage() {}

func (x *UpdateTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTaskStatusResponse) GetShouldRetry() bool {
	if x != nil {
		return x.ShouldRetry
	}
	return false
}

type WorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType  string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"` // JSON object passed to step commands
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRequest) Reset() {
	*x = WorkflowRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRequest) ProtoMessage() {}

func (x *WorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRequest.ProtoReflect.Descriptor instead.
func (*WorkflowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{11}
}

func (x *WorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{12}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False if the workflow had already finished.
	Cancelled     bool `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_pkg_grpcapi_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcapi_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcapi_api_proto_rawDescGZIP(), []int{13}
}

func (x *CancelWorkflowResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

var File_pkg_grpcapi_api_proto protoreflect.FileDescriptor

const file_pkg_grpcapi_api_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/grpcapi/api.proto\x12\agrpcapi\"\x84\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\"[\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xe0\x01\n" +
	"\x11ClientTaskRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12.\n" +
	"\x13retry_delay_seconds\x18\x04 \x01(\x05R\x11retryDelaySeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12!\n" +
	"\fscheduled_at\x18\x06 \x01(\x03R\vscheduledAt\"-\n" +
	"\x12ClientTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"2\n" +
	"\x12CancelTaskResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"e\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\rR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bdraining\x18\x03 \x01(\bR\bdraining\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x9c\x01\n" +
	"\x17UpdateTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.grpcapi.TaskStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"=\n" +
	"\x18UpdateTaskStatusResponse\x12!\n" +
	"\fshould_retry\x18\x01 \x01(\bR\vshouldRetry\"U\n" +
	"\x0fWorkflowRequest\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\"3\n" +
	"\x10WorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"8\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"6\n" +
	"\x16CancelWorkflowResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled*?\n" +
	"\n" +
	"TaskStatus\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\f\n" +
	"\bCOMPLETE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\x95\x01\n" +
	"\rWorkerService\x12;\n" +
	"\n" +
	"SubmitTask\x12\x14.grpcapi.TaskRequest\x1a\x15.grpcapi.TaskResponse\"\x00\x12G\n" +
	"\n" +
	"CancelTask\x12\x1a.grpcapi.CancelTaskRequest\x1a\x1b.grpcapi.CancelTaskResponse\"\x002\xe9\x03\n" +
	"\x12CoordinatorService\x12G\n" +
	"\n" +
	"SubmitTask\x12\x1a.grpcapi.ClientTaskRequest\x1a\x1b.grpcapi.ClientTaskResponse\"\x00\x12G\n" +
	"\n" +
	"CancelTask\x12\x1a.grpcapi.CancelTaskRequest\x1a\x1b.grpcapi.CancelTaskResponse\"\x00\x12H\n" +
	"\rSendHeartbeat\x12\x19.grpcapi.HeartbeatRequest\x1a\x1a.grpcapi.HeartbeatResponse\"\x00\x12Y\n" +
	"\x10UpdateTaskStatus\x12 .grpcapi.UpdateTaskStatusRequest\x1a!.grpcapi.UpdateTaskStatusResponse\"\x00\x12G\n" +
	"\x0eSubmitWorkflow\x12\x18.grpcapi.WorkflowRequest\x1a\x19.grpcapi.WorkflowResponse\"\x00\x12S\n" +
	"\x0eCancelWorkflow\x12\x1e.grpcapi.CancelWorkflowRequest\x1a\x1f.grpcapi.CancelWorkflowResponse\"\x00B.Z,github.com/ChinmayNoob/conductor/pkg/grpcapib\x06proto3"

var (
	file_pkg_grpcapi_api_proto_rawDescOnce sync.Once
	file_pkg_grpcapi_api_proto_rawDescData []byte
)

func file_pkg_grpcapi_api_proto_rawDescGZIP() []byte {
	file_pkg_grpcapi_api_proto_rawDescOnce.Do(func() {
		file_pkg_grpcapi_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpcapi_api_proto_rawDesc), len(file_pkg_grpcapi_api_proto_rawDesc)))
	})
	return file_pkg_grpcapi_api_proto_rawDescData
}

var file_pkg_grpcapi_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_grpcapi_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_grpcapi_api_proto_goTypes = []any{
	(TaskStatus)(0),                  // 0: grpcapi.TaskStatus
	(*TaskRequest)(nil),              // 1: grpcapi.TaskRequest
	(*TaskResponse)(nil),             // 2: grpcapi.TaskResponse
	(*ClientTaskRequest)(nil),        // 3: grpcapi.ClientTaskRequest
	(*ClientTaskResponse)(nil),       // 4: grpcapi.ClientTaskResponse
	(*CancelTaskRequest)(nil),        // 5: grpcapi.CancelTaskRequest
	(*CancelTaskResponse)(nil),       // 6: grpcapi.CancelTaskResponse
	(*HeartbeatRequest)(nil),         // 7: grpcapi.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 8: grpcapi.HeartbeatResponse
	(*UpdateTaskStatusRequest)(nil),  // 9: grpcapi.UpdateTaskStatusRequest
	(*UpdateTaskStatusResponse)(nil), // 10: grpcapi.UpdateTaskStatusResponse
	(*WorkflowRequest)(nil),          // 11: grpcapi.WorkflowRequest
	(*WorkflowResponse)(nil),         // 12: grpcapi.WorkflowResponse
	(*CancelWorkflowRequest)(nil),    // 13: grpcapi.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),   // 14: grpcapi.CancelWorkflowResponse
}
var file_pkg_grpcapi_api_proto_depIdxs = []int32{
	0,  // 0: grpcapi.UpdateTaskStatusRequest.status:type_name -> grpcapi.TaskStatus
	1,  // 1: grpcapi.WorkerService.SubmitTask:input_type -> grpcapi.TaskRequest
	5,  // 2: grpcapi.WorkerService.CancelTask:input_type -> grpcapi.CancelTaskRequest
	3,  // 3: grpcapi.CoordinatorService.SubmitTask:input_type -> grpcapi.ClientTaskRequest
	5,  // 4: grpcapi.CoordinatorService.CancelTask:input_type -> grpcapi.CancelTaskRequest
	7,  // 5: grpcapi.CoordinatorService.SendHeartbeat:input_type -> grpcapi.HeartbeatRequest
	9,  // 6: grpcapi.CoordinatorService.UpdateTaskStatus:input_type -> grpcapi.UpdateTaskStatusRequest
	11, // 7: grpcapi.CoordinatorService.SubmitWorkflow:input_type -> grpcapi.WorkflowRequest
	13, // 8: grpcapi.CoordinatorService.CancelWorkflow:input_type -> grpcapi.CancelWorkflowRequest
	2,  // 9: grpcapi.WorkerService.SubmitTask:output_type -> grpcapi.TaskResponse
	6,  // 10: grpcapi.WorkerService.CancelTask:output_type -> grpcapi.CancelTaskResponse
	4,  // 11: grpcapi.CoordinatorService.SubmitTask:output_type -> grpcapi.ClientTaskResponse
	6,  // 12: grpcapi.CoordinatorService.CancelTask:output_type -> grpcapi.CancelTaskResponse
	8,  // 13: grpcapi.CoordinatorService.SendHeartbeat:output_type -> grpcapi.HeartbeatResponse
	10, // 14: grpcapi.CoordinatorService.UpdateTaskStatus:output_type -> grpcapi.UpdateTaskStatusResponse
	12, // 15: grpcapi.CoordinatorService.SubmitWorkflow:output_type -> grpcapi.WorkflowResponse
	14, // 16: grpcapi.CoordinatorService.CancelWorkflow:output_type -> grpcapi.CancelWorkflowResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_grpcapi_api_proto_init() }
func file_pkg_grpcapi_api_proto_init() {
	if File_pkg_grpcapi_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpcapi_api_proto_rawDesc), len(file_pkg_grpcapi_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_grpcapi_api_proto_goTypes,
		DependencyIndexes: file_pkg_grpcapi_api_proto_depIdxs,
		EnumInfos:         file_pkg_grpcapi_api_proto_enumTypes,
		MessageInfos:      file_pkg_grpcapi_api_proto_msgTypes,
	}.Build()
	File_pkg_grpcapi_api_proto = out.File
	file_pkg_grpcapi_api_proto_goTypes = nil
	file_pkg_grpcapi_api_proto_depIdxs = nil
}
